/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

module adder(clk, rst, a, b, sum);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire [7:0] _072_;
  wire [7:0] _073_;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [7:0] sum;
  wire [7:0] sum;
  sky130_fd_sc_hd__nand2_1 _074_ (
    .A(_033_),
    .B(_049_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _075_ (
    .A(_032_),
    .B(_048_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor2_1 _076_ (
    .A(_033_),
    .B(_049_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _077_ (
    .A(_056_),
    .SLEEP(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__o21ai_0 _078_ (
    .A1(_057_),
    .A2(_058_),
    .B1(_056_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__xnor2_1 _079_ (
    .A(_034_),
    .B(_050_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xnor2_1 _080_ (
    .A(_060_),
    .B(_061_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__maj3_1 _081_ (
    .A(_034_),
    .B(_050_),
    .C(_060_),
    .X(_062_)
  );
  sky130_fd_sc_hd__xnor2_1 _082_ (
    .A(_035_),
    .B(_051_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xnor2_1 _083_ (
    .A(_062_),
    .B(_063_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__maj3_1 _084_ (
    .A(_035_),
    .B(_051_),
    .C(_062_),
    .X(_064_)
  );
  sky130_fd_sc_hd__xnor2_1 _085_ (
    .A(_036_),
    .B(_052_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _086_ (
    .A(_064_),
    .B(_065_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__maj3_1 _087_ (
    .A(_036_),
    .B(_052_),
    .C(_064_),
    .X(_066_)
  );
  sky130_fd_sc_hd__xnor2_1 _088_ (
    .A(_037_),
    .B(_053_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xnor2_1 _089_ (
    .A(_066_),
    .B(_067_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__maj3_1 _090_ (
    .A(_037_),
    .B(_053_),
    .C(_066_),
    .X(_068_)
  );
  sky130_fd_sc_hd__xnor2_1 _091_ (
    .A(_038_),
    .B(_054_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__xnor2_1 _092_ (
    .A(_068_),
    .B(_069_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__maj3_1 _093_ (
    .A(_038_),
    .B(_054_),
    .C(_068_),
    .X(_070_)
  );
  sky130_fd_sc_hd__xnor2_1 _094_ (
    .A(_039_),
    .B(_055_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__xnor2_1 _095_ (
    .A(_070_),
    .B(_071_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xor2_1 _096_ (
    .A(_032_),
    .B(_048_),
    .X(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _097_ (
    .A(_057_),
    .B(_059_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__dfrtp_1 _098_ (
    .CLK(clk),
    .D(_072_[0]),
    .Q(sum[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _099_ (
    .CLK(clk),
    .D(_073_[1]),
    .Q(sum[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _100_ (
    .CLK(clk),
    .D(_073_[2]),
    .Q(sum[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _101_ (
    .CLK(clk),
    .D(_073_[3]),
    .Q(sum[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _102_ (
    .CLK(clk),
    .D(_073_[4]),
    .Q(sum[4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _103_ (
    .CLK(clk),
    .D(_073_[5]),
    .Q(sum[5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _104_ (
    .CLK(clk),
    .D(_073_[6]),
    .Q(sum[6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _105_ (
    .CLK(clk),
    .D(_073_[7]),
    .Q(sum[7]),
    .RESET_B(rst)
  );
  assign _073_[0] = _072_[0];
  assign _033_ = a[1];
  assign _049_ = b[1];
  assign _032_ = a[0];
  assign _048_ = b[0];
  assign _073_[2] = _042_;
  assign _035_ = a[3];
  assign _051_ = b[3];
  assign _034_ = a[2];
  assign _050_ = b[2];
  assign _073_[3] = _043_;
  assign _036_ = a[4];
  assign _052_ = b[4];
  assign _073_[4] = _044_;
  assign _037_ = a[5];
  assign _053_ = b[5];
  assign _073_[5] = _045_;
  assign _038_ = a[6];
  assign _054_ = b[6];
  assign _073_[6] = _046_;
  assign _039_ = a[7];
  assign _055_ = b[7];
  assign _073_[7] = _047_;
  assign _072_[0] = _040_;
  assign _073_[1] = _041_;
endmodule
